version: 0.2

env:
  variables:
    NODE_ENV: test

phases:
  install:
    commands:
      - echo Installing dependences...
      - npm install

  pre_build:
    commands:
      - echo Running tests and generating reports...
      # Generate JSON report
      - npx jest --runInBand --json --outputFile=test-results.json
      # Generate HTML report (using reporter config in package.json)
      - npx jest

  build:
    commands:
      - echo Building React App...
      - npm run build

artifacts:
  files:
    - test-results.json
    - test-report.html
    - build/**         # Build folder for deployment (only if React)
  discard-paths: yes
